
GET http://localhost:3001/api/persons/ HTTP/1.1

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "valentine",
    "number": "090330039239"
}

# DELETE http://localhost:3001/api/persons/3 HTTP/1.1