
# GET http://localhost:3005/api/persons/ HTTP/1.1

POST http://localhost:3005/api/persons/
Content-Type: application/json

{
    "name": "eberechukwu",
    "number": "090330000000"
}

# DELETE http://localhost:3001/api/persons/3 HTTP/1.1

# GET http://localhost:3005/api/persons/5f8eaf0e7e0a1b9d885873a1 HTTP/1.1

# GET http://localhost:3005/info HTTP/1.1

# HTTP/1.1 200 OK
# X-Powered-By: Express
# Access-Control-Allow-Origin: *
# Content-Type: application/json; charset=utf-8
# Content-Length: 78
# ETag: W/"4e-HAptJMvi+8vk+n2zWERasiAiOWk"
# Date: Fri, 23 Oct 2020 00:20:09 GMT
# Connection: close

# {
#   "name": "eberechukwu",
#   "number": "090330000000",
#   "id": "5f9221b983b1c834c40885f6"
# }